import { HorizontalBox, Palette, ListView } from "std-widgets.slint";
import { Page } from "../pages/page.slint";
import { CategoryCard, CategoryCardData } from "category_card.slint";

export component CategoriesCarousel inherits Rectangle {
        in property <[CategoryCardData]> categories : [
          { name: "card0",
            id: "card0",
            is_selected:true
           },
          { name: "card1"},
          { name: "card2"},
          { name: "card3"},
          { name: "card4"},
          { name: "card5"},
          { name: "card6"},
          { name: "card7"},
          { name: "card8"},
          { name: "card9"},
          { name: "card10"},
        ];

        Flickable {
          VerticalLayout {
            for category in categories:
                    CategoryCard {
                      cardData: category;
        }
}}}