
import { HorizontalBox, Palette, VerticalBox, Button } from "std-widgets.slint";

export struct ItemCardData {
    id: string,
    name: string,
    image_url: image,
    price :int ,
    qttyInCart  :int ,
    qttyInStore :int ,
}

export global ItemCardCallback {
    callback itemInc(string);
    callback itemDec(string);
}
export global ItemCardSize {
    out property <length> width: 150px;
    out property <length> height: 200px;
}

export component ItemCard inherits Rectangle {
    in property <ItemCardData> cardData:{
        name:"Card1" ,
        price:1,
        qttyInCart  :2 ,
        qttyInStore :4 ,
    };

    border-color: blue;
    border-width: 2px;
    width: ItemCardSize.width;
    height: ItemCardSize.height;
    VerticalBox {
        Image {
            vertical-stretch: 1;
            
        }
        Text {
            text: cardData.name;
        }

        HorizontalBox {

            Text {
                text: cardData.price;
            }
            Text {
                text: "/";
            }
            Text {
                text: cardData.qttyInStore ;
            }
    }
        HorizontalBox {
            Button {
                text: "-";
                clicked => {ItemCardCallback.itemDec(cardData.id)}
            }
            Text {
                text: cardData.qttyInCart;
            }
            Button {
                text: "+";
                clicked => {ItemCardCallback.itemInc(cardData.id)}
            }
        }
}
}






