import { ScrollView, HorizontalBox, Palette, VerticalBox, GridBox } from "std-widgets.slint";
import { GridCard, GridCardData, GridCardSize } from "grid_card.slint";


export component ProductGrid inherits Rectangle{
    border-color: green;
    border-width: 2px;

    property <int> col_count: floor(root.width/(GridCardSize.width+card_spacing_px));
    property <int> row_count: floor(root.height/(GridCardSize.height+card_spacing_px));       
    property <int> card_spacing: 10;    
    property <length> card_spacing_px: card_spacing*1px;    

    ScrollView {

    in property <[GridCardData]> cards : [
          { name: "card1"},
          { name: "card2"},
          { name: "card3"},
          { name: "card4"},
          { name: "card5"},
          { name: "card6"},
          { name: "card7"},
          { name: "card8"},
          { name: "card9"},
          { name: "card10"},
        ];
    
    
    for card[index] in cards:
        GridCard {
            x: root.card_spacing_px + mod(index, root.col_count) * (GridCardSize.width + root.card_spacing_px);
            y: root.card_spacing_px + floor(index/ root.row_count) * (GridCardSize.height + root.card_spacing_px);
            cardData: { name: "Card" + index };
        }
}
}