import { ListView, HorizontalBox, Palette, VerticalBox, GridBox } from "std-widgets.slint";
import { GridCard, GridCardData, GridCardSize } from "grid_card.slint";


export component ProductGrid inherits Rectangle{
    border-color: green;
    border-width: 2px;

    in property <[GridCardData]> cards : [
          { name: "card0"},
          { name: "card1"},
          { name: "card2"},
          { name: "card3"},
          { name: "card4"},
          { name: "card5"},
          { name: "card6"},
          { name: "card7"},
          { name: "card8"},
          { name: "card9"},
          { name: "card10"},
        ];
    property <int> col_count: 3;
    property <int> row_count: cards.length/col_count;
    property <int> card_spacing: 10;    
    property <length> card_spacing_px: card_spacing*1px;    

    ListView {
        for row in row_count:
            HorizontalBox{
                for col in col_count:
                    Rectangle{
                        width: GridCardSize.width;
                        height: GridCardSize.height;
                        property <int> idx: (row * col_count) + col;
                        if idx < cards.length: 
                            GridCard {
                                cardData: { name: "Index:" +idx};
                            }
                    }
        }
}
}