import { HorizontalBox, Palette, VerticalBox } from "std-widgets.slint";
import { Page } from "page.slint";
import { CategoriesCarousel } from "../components/categories_carousel.slint";
import { ItemsGrid } from "../components/items_grid.slint";

export component Home inherits Page {
    HorizontalLayout {
        preferred-height: 100%;
        preferred-width: 100%;
        CategoriesCarousel {}
        ItemsGrid {}

  }
        
}