import { Button, VerticalBox,Palette } from "std-widgets.slint";
import { Header } from "components/header.slint";
import { Home } from "pages/home.slint";
import { CategoryCardCallback } from "components/category_card.slint";
import { ItemCardCallback  } from "components/item_card.slint";



export { CategoryCardCallback, ItemCardCallback }

export component AppWindow inherits Window {
    preferred-height: 720px;
    preferred-width: 800px; 
    in-out property<int> counter: 42;
    VerticalLayout {
        height: parent.height;
        width: parent.width;
        Header {
            height: 100px;
        }
        Home {
            vertical-stretch: 1;
        }
    }
}
